name: Build/Publish artifacts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Add macOS certs
        if: matrix.os == 'macos-latest'
        run: chmod +x ./.github/add-macos-certificate.sh && ./.github/add-macos-certificate.sh
        env:
          APPLE_CERTIFICATES: ${{ secrets.APPLE_CERTIFICATES }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Build
        run: |
          yarn make -- --arch x64
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'macOS' }}
        with:
          name: macos-build
          path: |
            out/make/**/*.zip
            out/make/**/*.dmg
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          name: windows-build
          path: |
            out/make/**/*.nupkg
            out/make/**/*.exe
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Linux' }}
        with:
          name: linux-build
          path: |
            out/make/**/*.rpm
            out/make/**/*.deb
