name: Build/Publish artifacts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run make

      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            out/make/deb
            out/make/rpm
            out/make/zip
            out/make/squirrel.windows
