name: Build/Publish artifacts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run make -- --arch x64,arm64

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'macOS' }}
        with:
          name: macos-build
          path: |
            artifacts/*.zip
            artifacts/*.dmg
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          name: windows-build
          path: |
            artifacts/*.nupkg
            artifacts/*.exe
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Linux' }}
        with:
          name: linux-build
          path: |
            artifacts/*.rpm
            artifacts/*.deb
